{"name": "test_mul_002", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <TestCases.test_file1.Test001 object at 0x00000288AA372B40>, demo_fixture = None\n\n    @pytest.mark.sanity\n    @pytest.mark.group2\n    \n    def test_mul_002(self,demo_fixture):\n        a = 2\n        b = 2\n        mul = a * b\n        print(\"Mul of a * b =\" + str(mul))\n        if mul == 5:\n            assert True\n        else:\n>           assert False\nE           assert False\n\nTestCases\\test_file1.py:106: AssertionError"}, "start": 1722500044768, "stop": 1722500044769, "uuid": "8550aa10-aee8-46e2-af5a-805ff1bfd70d", "historyId": "9c38436ab44f54572889c6141f850983", "testCaseId": "9c38436ab44f54572889c6141f850983", "fullName": "TestCases.test_file1.Test001#test_mul_002", "labels": [{"name": "tag", "value": "group2"}, {"name": "tag", "value": "sanity"}, {"name": "parentSuite", "value": "TestCases"}, {"name": "suite", "value": "test_file1"}, {"name": "subSuite", "value": "Test001"}, {"name": "host", "value": "DESKTOP-16HA8VL"}, {"name": "thread", "value": "12940-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_file1"}]}