{"uuid": "2a0aee33-2fd2-492e-96c9-e61a9c0975bf", "children": ["5d8b8e5c-91fc-4bce-a1f8-aa745858b5db"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: session not created: DevToolsActivePort file doesn't exist\nStacktrace:\n\tGetHandleVerifier [0x00007FF61F189632+30946]\n\t(No symbol) [0x00007FF61F13E3C9]\n\t(No symbol) [0x00007FF61F036FDA]\n\t(No symbol) [0x00007FF61F075CF5]\n\t(No symbol) [0x00007FF61F0716BC]\n\t(No symbol) [0x00007FF61F06C4FA]\n\t(No symbol) [0x00007FF61F0B78B9]\n\t(No symbol) [0x00007FF61F0B6F20]\n\t(No symbol) [0x00007FF61F0AC813]\n\t(No symbol) [0x00007FF61F07A6E5]\n\t(No symbol) [0x00007FF61F07B021]\n\tGetHandleVerifier [0x00007FF61F2BF83D+1301229]\n\tGetHandleVerifier [0x00007FF61F2CBDB7+1351783]\n\tGetHandleVerifier [0x00007FF61F2C2A03+1313971]\n\tGetHandleVerifier [0x00007FF61F1BDD06+245686]\n\t(No symbol) [0x00007FF61F14758F]\n\t(No symbol) [0x00007FF61F143804]\n\t(No symbol) [0x00007FF61F143992]\n\t(No symbol) [0x00007FF61F13A3EF]\n\tBaseThreadInitThunk [0x00007FF9C2027034+20]\n\tRtlUserThreadStart [0x00007FF9C40026A1+33]\n\n", "trace": "  File \"C:\\Python\\Lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python\\Lib\\site-packages\\_pytest\\fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Python2023\\PythonSeleniumPractice\\OrangeHrmPytest24\\TestCases\\conftest.py\", line 33, in setup\n    driver = webdriver.Chrome(options=chrome_options)  # Initialize headless Chrome WebDriver\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python\\Lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"C:\\Python\\Lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 56, in __init__\n    super().__init__(\n  File \"C:\\Python\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 205, in __init__\n    self.start_session(capabilities)\n  File \"C:\\Python\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 289, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Python\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Python\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1723537075192, "stop": 1723537149355}], "start": 1723537075192, "stop": 1723537149515}