[31mCRITICAL[0m Test_Orange_HRM:test_OrangeHRM_Login.py:52 test_Orange_Hrm_Login_002 is started
[32mINFO    [0m Test_Orange_HRM:test_OrangeHRM_Login.py:54 Opening the browser
[32mINFO    [0m Test_Orange_HRM:test_OrangeHRM_Login.py:61 Entering Username -->Admin
[32mINFO    [0m Test_Orange_HRM:test_OrangeHRM_Login.py:66 Entering Username -->admin123
[32mINFO    [0m Test_Orange_HRM:test_OrangeHRM_Login.py:70 Clicking on Login Button
[32mINFO    [0m Test_Orange_HRM:test_OrangeHRM_Login.py:71 Verifying login Status
[32mINFO    [0m Test_Orange_HRM:test_OrangeHRM_Login.py:73 test_Orange_Hrm_Login_002 is Passed
[32mINFO    [0m Test_Orange_HRM:test_OrangeHRM_Login.py:75 clicking on Menu Button
[32mINFO    [0m Test_Orange_HRM:test_OrangeHRM_Login.py:77 Clicking on logout button
[32mINFO    [0m Test_Orange_HRM:test_OrangeHRM_Login.py:79 Taking on screenshot
[32mINFO    [0m Test_Orange_HRM:test_OrangeHRM_Login.py:86 Browser is closed
[32mINFO    [0m Test_Orange_HRM:test_OrangeHRM_Login.py:88 test_Orange_Hrm_Login_002 is Completed
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:872 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000029327D4C5D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/71c9f2763ae09fa7000a47a066b5a344
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:872 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000029327D4CD10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/71c9f2763ae09fa7000a47a066b5a344
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:872 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000029327D4D4D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/71c9f2763ae09fa7000a47a066b5a344