[31mCRITICAL[0m Test_Orange_HRM:test_OrangeHRM_Login.py:47 test_Orange_Hrm_Login_002 is started
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000287CA852B70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/3f73ba0ccf95fdf6b8653b95a95612c8
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000287CA8526F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/3f73ba0ccf95fdf6b8653b95a95612c8
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000287CA852C60>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/3f73ba0ccf95fdf6b8653b95a95612c8