[31mCRITICAL[0m Test_Orange_HRM:test_OrangeHRM_Login.py:23 test_Orange_Hrm_Login_001 is started
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000287CA851490>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/816efb279a5b021b793557d5034224fe
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000287CA850170>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/816efb279a5b021b793557d5034224fe
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000287CA851550>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/816efb279a5b021b793557d5034224fe